#release configuration
#Thu May 28 23:36:38 CDT 2026
projectVersionPolicyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
project.rel.sc.fiji\:OMEVisual=3.0.0
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.scm.sc.fiji\:OMEVisual.tag=HEAD
project.scm.sc.fiji\:OMEVisual.developerConnection=scm\:git\:git@github.com\:fiji/OMEVisual
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.sc.fiji\:OMEVisual.url=https\://github.com/fiji/OMEVisual
completedPhase=end-release
project.dev.sc.fiji\:OMEVisual=3.0.1-SNAPSHOT
scm.url=scm\:git\:https\://github.com/fiji/OMEVisual
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.sc.fiji\:OMEVisual.connection=scm\:git\:https\://github.com/fiji/OMEVisual
scm.tag=OMEVisual-3.0.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
